


//profiles API.


###
POST  http://127.0.0.1:3000/review/create-reviews HTTP/1.1
Content-Type: application/json 

{
"uid": 281049679,
"profile": "User Profile URL or String",
"anime_uid": 67890,
"text": "This is a sample review text.",
"score": 8,
"scores": 9,
"link": "https://example.com/link-to-something"
}


###
POST  http://127.0.0.1:3000/profiles/delete-profiles HTTP/1.1
Content-Type: application/json 

{
    "profile": "JohnDoe"
}


###
POST  http://127.0.0.1:3000/profiles/update-profiles HTTP/1.1
Content-Type: application/json 

{
    "profile": "JohnDoe",
    "gender": "Male",
    "birthday": "2001-01-01",
    "favorites_anime": [123, 456, 789],
    "link": "http://lamjed.com/myprofile"
}



###
GET http://127.0.0.1:3000/profiles/read-profiles/profile/JohnDoe  HTTP/1.1
Content-Type: application/json 


###
GET http://127.0.0.1:3000/profiles/readByGender-profiles/gender/Male  HTTP/1.1
Content-Type: application/json 