###
POST  http://127.0.0.1:3000/anime/create-anime HTTP/1.1
Content-Type: application/json 

{
    "anime_uid": 281049679,
    "title": "Test Anime",
    "synopsis": "This is a placeholder synopsis for the test anime. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "genre": "Action, Adventure, Fantasy",
    "aired": "Spring 2024",
    "episodes": 12,
    "members": 5000,
    "popularity": 1234,
    "ranked": 50,
    "score": 8.5,
    "img_url": "https://example.com/test-anime-image.jpg",
    "link": "https://example.com/test-anime"
}


###
POST  http://127.0.0.1:3000/anime/update-anime HTTP/1.1
Content-Type: application/json 

{
    "uid": 281049679,
    "title": "updated test",
    "synopsis": "This is a placeholder synopsis for the test anime. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "genre": "Action, Adventure, Fantasy",
    "aired": "Spring 2024",
    "episodes": 12,
    "members": 5000,
    "popularity": 1234,
    "ranked": 55,
    "score": 8.5,
    "img_url": "https://example.com/test-anime-image.jpg",
    "link": "https://example.com/test-anime"
}


###
POST  http://127.0.0.1:3000/anime/delete-anime HTTP/1.1
Content-Type: application/json 

{
    "anime_uid": 281049679
}


###
GET http://127.0.0.1:3000/anime/read-anime/281049679 HTTP/1.1
Content-Type: application/json 


###
GET http://127.0.0.1:3000/anime/readAll-anime/281049679 HTTP/1.1
Content-Type: application/json 


###
GET http://127.0.0.1:3000/anime/readByrank-anime/ranked/54 HTTP/1.1
Content-Type: application/json 




//profiles API.


###
POST  http://127.0.0.1:3000/profiles/create-profiles HTTP/1.1
Content-Type: application/json 

{
    "profile": "JohnDoe",
    "gender": "Male",
    "birthday": "1990-01-01",
    "favorites_anime": [123, 456, 789],
    "link": "http://example.com/myprofile"
}


###
POST  http://127.0.0.1:3000/profiles/delete-profiles HTTP/1.1
Content-Type: application/json 

{
    "profile": "JohnDoe"
}


###
POST  http://127.0.0.1:3000/profiles/update-profiles HTTP/1.1
Content-Type: application/json 

{
    "profile": "JohnDoe",
    "gender": "Male",
    "birthday": "2001-01-01",
    "favorites_anime": [123, 456, 789],
    "link": "http://lamjed.com/myprofile"
}



###
GET http://127.0.0.1:3000/profiles/read-profiles/profile/JohnDoe  HTTP/1.1
Content-Type: application/json 


###
GET http://127.0.0.1:3000/profiles/readByGender-profiles/gender/Male  HTTP/1.1
Content-Type: application/json 